config/routes.rb
Rails.application.routes.draw do

  root to: 'main#index'

  post  'fetch_data' => 'main#fetch_data'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController

  def index
  end

  def fetch_data
    @userdata = GetGithubInfo.new(github_param["username"]).perform
  end

  private

  def github_param
    params.permit(:username)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sh24 Test Application</title>
    <%= csrf_meta_tags %>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>

app/views/main/fetch_data.js.erb
<% if @userdata.blank? %>
  $(".resultBlock").hide();
  $(".alert").show();
<% else %>
  $(".alert").hide();
  $("#favoriteLang").text('<%= j @userdata[0] %>');
  $(".resultBlock").show();
<% end %>

app/views/main/index.html.erb
<div class="container">
  <div class="page-header">
    <h1>Learn favorite <i class="fa fa-github-alt"></i> language </h1>
  </div>
  <h1 class="lead">Enter a github username.</h1>
  <%= form_tag fetch_data_path, class: "form-inline", remote: true do %>
    <div class="form-group">
      <%= text_field_tag 'username', nil, class: "form-control", placeholder: "Username", required: true %>
    </div>
    <%= submit_tag "Start", class: "btn btn-default" %>
  <% end %>
  <br />
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <strong>User not found!</strong>
  </div>
  <div class="resultBlock">
    <h2>Favorite language:</h2>
    <span id="favoriteLang"></span>
  </div>
  <hr />
  <div class="tweet-container">
    <div class="tweet">
      <img src="https://pbs.twimg.com/profile_images/1844491454/horse-js.png" alt="" />
      <div class="t_body">
        <span class="username">horse_js</span>
        <span class="t_text">as much as I want to be, I'm not <a href="#" class="mention">@horse_js</a></span>
        <span class="date">7 days</span>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript" charset="utf-8">
  $(function(){
    $("form").on("submit", function() {
      $(".resultBlock, .alert").hide();
    });
  });
</script>